[package]
name = "pyruve"
version = "0.2.0"
authors = ["Mikhail Dengin <denginm@gmail.com>"]
license = "MIT"
description = "Automatically activate Python virtual environments on directory change"
repository = "https://github.com/insomnes/pyruve/"
readme = "README.md"
keywords = ["python", "virtualenv", "venv", "shell"]
categories = ["command-line-utilities", "development-tools"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
